#ifndef SDIZO_PROJEKT_1_RANDOMINPUTDATAGENERATOR_H
#define SDIZO_PROJEKT_1_RANDOMINPUTDATAGENERATOR_H

class RandomInputDataGenerator {
public:
    void Generator();
};

#endif //SDIZO_PROJEKT_1_RANDOMINPUTDATAGENERATOR_H
